Repository pulumi/pulumi-newrelic, pull requests merged in 2019-06, with the labels that each got.

#4 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#5 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/alertChannel.ts
  sdk/nodejs/alertCondition.ts
  sdk/nodejs/alertPolicy.ts
  sdk/nodejs/alertPolicyChannel.ts
  sdk/nodejs/dashboard.ts
  sdk/nodejs/infraAlertCondition.ts
  sdk/nodejs/nrqlAlertCondition.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/synthetics/alertCondition.ts
  sdk/nodejs/synthetics/monitor.ts
  sdk/nodejs/synthetics/monitorScript.ts
Labels: area/providers

#6 Addition of a simple NewRelic example
  examples/alertpolicy/.gitignore
  examples/alertpolicy/Pulumi.yaml
  examples/alertpolicy/index.ts
  examples/alertpolicy/package.json
  examples/alertpolicy/tsconfig.json
  examples/examples_test.go
Labels: impact/no-changelog-required

#9 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#11 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required
